// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VoiceCaptureService.Infrastructure.Data;

#nullable disable

namespace VoiceCaptureService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260701171936_ChangedRecordingMetadataColumns")]
    partial class ChangedRecordingMetadataColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VoiceCaptureService.Domain.Recording.Entities.RecordingSession", b =>
                {
                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("RecordingId");

                    b.ToTable("RecordingSessions", (string)null);
                });

            modelBuilder.Entity("VoiceCaptureService.Domain.Recording.Entities.RecordingSession", b =>
                {
                    b.OwnsOne("VoiceCaptureService.Domain.Recording.ValueObjects.RecordingMetadata", "RecordingMetadata", b1 =>
                        {
                            b1.Property<Guid>("RecordingSessionRecordingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BitsPerSample")
                                .HasColumnType("integer")
                                .HasColumnName("BitsPerSample");

                            b1.Property<int>("ChannelCount")
                                .HasColumnType("integer")
                                .HasColumnName("ChannelCount");

                            b1.Property<string>("MimeType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("MimeType");

                            b1.Property<int>("SampleRate")
                                .HasColumnType("integer")
                                .HasColumnName("SampleRate");

                            b1.HasKey("RecordingSessionRecordingId");

                            b1.ToTable("RecordingSessions");

                            b1.WithOwner()
                                .HasForeignKey("RecordingSessionRecordingId");
                        });

                    b.Navigation("RecordingMetadata");
                });
#pragma warning restore 612, 618
        }
    }
}
