syntax = "proto3";

option csharp_namespace = "RecordingGrpcService.Grpc.Protos";

import "google/protobuf/Empty.proto";

package recordingchunk;

service RecordingChunkService {
  rpc SaveRecordingChunk (RecordingChunkRequest) returns (google.protobuf.Empty);
  rpc GetRecordingChunk (GetRecordingChunkRequest) returns (GetRecordingChunkResponse);
  rpc UpdateRecordingChunk (UpdateRecordingChunkRequest) returns (google.protobuf.Empty);
}

message RecordingChunkRequest {
  RecordingChunkDto recording_chunk = 1;
}

message GetRecordingChunkRequest {
  string chunk_id = 1;
}

message GetRecordingChunkResponse {
  repeated RecordingChunkDto recording_chunk = 1;
}

message UpdateRecordingChunkRequest {
  string chunk_id = 1;
  string storage_path = 2;
}

message RecordingChunkDto {  
  string chunk_id = 1;
  string recording_id = 2;  
  int32 sequence_number	= 3;
  string storage_path = 4;
}